previewsExpireAfterDays: 3

services:
  - type: web
    name: mui-olivier-tools
    env: node
    rootDir: ./
    buildCommand: pnpm install && pnpm build
    startCommand: node_modules/.bin/toolpad start
    pullRequestPreviewsEnabled: true
    plan: free
    envVars:
      - fromGroup: npm
      - fromGroup: github
      - fromGroup: basic-auth
      - key: NODE_VERSION
        value: 18
