# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.48/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: GitHub users
  display: shell
  content:
    - component: Text
      name: text1
      layout:
        columnSize: 1
      props:
        value: GitHub users
        variant: h3
    - component: DataGrid
      name: dataGrid
      layout:
        columnSize: 1
      props:
        rows:
          $$jsExpression: |
            listUser.data
        height: 324
        columns:
          - field: login
            type: string
            width: 177
          - field: type
            type: string
          - field: site_admin
            type: boolean
    - component: Text
      name: text
      layout:
        columnSize: 1
      props:
        value: Invite new user
        variant: h4
    - component: TextField
      name: username
      layout:
        columnSize: 1
      props:
        fullWidth: false
        label: new user GitHub username
        sx:
          width: 300
    - component: Button
      name: button
      layout:
        columnSize: 1
      props:
        fullWidth: false
        loading:
          $$jsExpression: |
            inviteUser.isLoading
        content: Invite
        onClick:
          $$jsExpressionAction: inviteUser.call()
        disabled:
          $$jsExpression: |
            username.value === ""
    - component: Text
      name: text2
      layout:
        columnSize: 1
      props:
        loading: false
        mode: markdown
        value:
          $$jsExpression: |
            `response:

            \`\`\`json
            ${JSON.stringify(inviteUser.data, null, 2)}
            \`\`\`
            `
  queries:
    - name: inviteUser
      mode: mutation
      query:
        function: githubInviteUser
        kind: local
      parameters:
        - name: username
          value:
            $$jsExpression: |
              username.value
    - name: listUser
      query:
        function: githubListUsers
        kind: local
  alias:
    - gIr39w1
  displayName: GitHub users
