# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.51/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: npm users
  content:
    - component: Text
      name: text1
      layout:
        columnSize: 1
      props:
        value: npm users
        variant: h3
    - component: PageRow
      name: pageRow
      props:
        justifyContent: start
      children:
        - component: Text
          name: text5
          props:
            value: "org name:"
          layout:
            horizontalAlign: start
            verticalAlign: center
            columnSize: 0.31949685534591193
        - component: Select
          name: select
          layout:
            columnSize: 1.6805031446540881
          props:
            fullWidth: false
            options:
              - value: mui
                label: "@mui"
              - value: toolpad
                label: "@toolpad"
              - value: pigment-css
                label: "@pigment-css"
              - value: base-ui
                label: "@base-ui"
              - value: base_ui
                label: "@base_ui"
              - value: base-ui-components
                label: "@base-ui-components"
            defaultValue: mui
            name: ""
    - component: DataGrid
      name: dataGrid
      layout:
        columnSize: 1
      props:
        rows:
          $$jsExpression: |
            listUser.data
        height: 322
        columns:
          - field: name
            type: string
            width: 156
          - field: role
            type: string
    - component: Text
      name: text
      layout:
        columnSize: 1
      props:
        value: Invite new user
        variant: h4
    - component: TextField
      name: slug
      layout:
        columnSize: 1
      props:
        fullWidth: false
        label: new user npm slug
        sx:
          width: 300
    - component: Button
      name: button
      layout:
        columnSize: 1
      props:
        loading:
          $$jsExpression: |
            inviteUser.isLoading
        fullWidth: false
        content: Invite
        onClick:
          $$jsExpressionAction: inviteUser.call()
        disabled:
          $$jsExpression: |
            slug.value === ""
    - component: Text
      name: text2
      layout:
        columnSize: 1
      props:
        value:
          $$jsExpression: |
            `response:

            \`\`\`json
            ${JSON.stringify(inviteUser.data, null, 2)}
            \`\`\`
            `
        loading: false
        mode: markdown
    - component: Text
      name: text4
      layout:
        columnSize: 1
      props:
        value: process.env.NPM_TOKEN
        variant: h4
    - component: Text
      name: text3
      layout:
        columnSize: 1
      props:
        mode: markdown
        value: >-
          Token to renew in
          https://www.npmjs.com/settings/oliviertassinari/tokens/granular-access-tokens/new.


          You need to set:


          - Packages and scopes: no permissions

          - Organizations: read and right to @mui, @toolpad, @pigment-css


          Set the expiration date to be 4 years.
  queries:
    - name: inviteUser
      mode: mutation
      query:
        function: npmInviteUser
        kind: local
      parameters:
        - name: org
          value:
            $$jsExpression: select.value
        - name: slug
          value:
            $$jsExpression: |
              slug.value
    - name: listUser
      query:
        function: npmListUsers
        kind: local
      parameters:
        - name: org
          value:
            $$jsExpression: select.value
  alias:
    - VACs-z8
  displayName: npm users
